# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='codigo',
            new_name='codigo_geral',
        ),
    ]
