# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170720_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ranking',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
